name: Setup go
description: xxx
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - shell: bash
      run: echo '${{ github.workspace }}/bin' >> $GITHUB_PATH