name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          path: scripts
          pattern: "*.sh"
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - run: exec_gofmt
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - run: exec_test
  goreleaser:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: build --snapshot --rm-dist
      - uses: actions/upload-artifact@v3
        with:
          name: providers
          path: dist/*
